### ISSUE TITLE
Controls included in Common vs Extended Unclear from Readme

### ISSUE THREAD

**Issue by DoctorBearPhD** [imagin-tech/Imagin.NET#92]
I just spent a while trying to figure out why I couldn't get some controls to appear, after rereading the readme about 15 times. 

Eventually, I figured out that there was an `Imagin.Controls.Extended` package.

Would you differentiate which Controls are included in the **Common** and **Extended** packages in the readme?

**Comment by imagin-tech** [comment]
**Do not install the packages.** I've revised the **README** to address the packages in question. I recommend downloading the repository as I am unable to update them at this time. When newer versions become available, I will update the **README** once again.
