### ISSUE TITLE
Missing files in latest release

### ISSUE THREAD

**Issue by jspaeth20** [imagin-tech/Imagin.NET#94]
![capture](https://user-images.githubusercontent.com/12473485/38155051-1ff200f8-343b-11e8-913c-43d32267ad86.PNG)

**Comment by imagin-tech** [comment]
I have no idea how that happened, but I'm going to take everything down and put it back up. Should be good in about ten minutes or so.

**Comment by imagin-tech** [comment]
New release 4.5.1 fixes this. Sorry again about that!
