### ISSUE TITLE
Property Grid Issues

### ISSUE THREAD

**Issue by jspaeth20** [imagin-tech/Imagin.NET#95]
I'm attempting to run the demo application from your latest 4.5.1 release and I'm getting issues when I try to open the property grid demo. The initial error I got was during the **Localizer.GetValue** which I found was due to passing the **result** variable into the method instead of the **key** variable (the IsNullOrEmpty error can be ignored).

![error_1](https://user-images.githubusercontent.com/12473485/38204573-15d09744-3669-11e8-9945-3fe4809d3af2.PNG)

Once I fixed this issue I got the following error which I haven't dug into much yet.

![error_2](https://user-images.githubusercontent.com/12473485/38204659-6bbfdf34-3669-11e8-94ad-6c52782a548c.PNG)

**Comment by imagin-tech** [comment]
It has to do with _CoercedVariantPropertyModel_, but I'm not sure exactly why. The issue actually occurs with all types that utilize it. I should have a fix up today or tomorrow.

**Comment by imagin-tech** [comment]
Silly mistake...

In _Proportions.cs_, it's the line,

`public override bool Equals(object o) => Equals((Proportions)o);`

Which, if changed to,

 `public override bool Equals(object o) => Equals(o as Proportions);`

works. This is all the result of an extension I defined to make equality checks easier to write.

This means all data structures that use this extension will need to be modified to accommodate the extension or the extension itself should be refactored; I'm leaning toward the latter.

Version _4.5.2_ will include these changes; I will close the issue once published later today.

**Comment by brambossche** [comment]
Hi, 
I downloaded latest commit and update the nuget packages. 
I still can't get the property grid running. 
Same issue as described. 
Any idea on how  I can make it work, or when there will be an update ?

**Comment by brambossche** [comment]
Hi, 

I could get it working when  changing the 4 castings which override Equals from Proportions

public override bool Equals(object o) => Equals(o as Proportions);
iso 
public override bool Equals(object o) => Equals((Proportions)o);

kind regards
Bram

**Comment by imagin-tech** [comment]
I have remedied the issue with equality as of release 5.0, which is up now. The names of some things have changed, but it is possible to correctly compare them now.
