### ISSUE TITLE
demo cant be run

### ISSUE THREAD

**Issue by yvz5** [imagin-tech/Imagin.NET#96]
when trying to start the demo project in vs 2017 with .net standard 2.0 following exception is being thrown:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Imagin.Colour.WPF
  StackTrace:
   at Imagin.Colour.Controls.ColorView.get_Components() in C:\Imagin.NET-master\Imagin.Colour.WPF\_Controls\ColorView\ColorView.xaml.cs:line 26
```

**Comment by thrmotta** [comment]
In order to fix that, change that line to:
`public Imagin.Colour.Controls.Collections.ComponentCollection Components
        {
            get
            {
                if( _colorModel == null )
                    _colorModel = Models.ColorModel.New( ColorModels.RGB );
                return _colorModel.Components;
            }
        }`

**Comment by thrmotta** [comment]
In order to fix that, change that line (26 from ColorView.xaml.cs) to:

```
public Imagin.Colour.Controls.Collections.ComponentCollection Components
{
    get
    {
        if( _colorModel == null )
            _colorModel = Models.ColorModel.New( ColorModels.RGB );
        return _colorModel.Components;
    }
}
```

**Comment by imagin-tech** [comment]
Release 5.0 should solve this. Demo now runs fine.
